// lib/academicClinic/documentIdentityProvenance.test.ts
//
// Phase 3 (Learner Report Architecture — document identity, provenance,
// school authority). Source-level guards, matching the established
// convention in careerConvergence.architecture.test.ts and
// orphanedClinicPageClosure.test.ts, proving:
//
// Guard A — the intelligence PDF identifies itself as EduNexus-generated
//           interpretation (provenance line present).
// Guard B — the intelligence PDF no longer brands itself "Learner Blueprint"
//           anywhere (the naming collision this phase's decision resolved).
// Guard C — the "Clinical recommendation:" / "clinically recommended"
//           phrasing (Phase 0's flagged misleading-authority language) is
//           gone from the generated prose.
// Guard D — the official Report Card's domain module (lib/core/report-cards.ts)
//           still imports zero AI/DeepSeek client — it must remain purely
//           school-recorded fact + mechanical derivation, never AI
//           interpretation, exactly as Phase 0 verified before this phase.
//
// Run: npx tsx --experimental-test-module-mocks --test lib/academicClinic/documentIdentityProvenance.test.ts
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = fileURLToPath(new URL('../../', import.meta.url))
function read(relPath: string): string {
  return readFileSync(`${REPO_ROOT}${relPath}`, 'utf8')
}

test('Guard A — the intelligence PDF header identifies EduNexus-generated interpretation, not a school-authored judgment', () => {
  const source = read('lib/academicClinic/pdfGenerator.tsx')
  assert.match(source, /Generated by EduNexus from available learner evidence/)
})

test('Guard B — the intelligence PDF no longer brands itself "Learner Blueprint" anywhere (rendered text, not comments)', () => {
  const source = read('lib/academicClinic/pdfGenerator.tsx')
  const codeLines = source.split('\n').filter(l => {
    const t = l.trim()
    return t.length > 0 && !t.startsWith('//') && !t.startsWith('*')
  })
  assert.doesNotMatch(codeLines.join('\n'), /Learner Blueprint/,
    'the intelligence PDF must not collide with the real, separate Blueprint product domain')
})

test('Guard C — "Clinical recommendation:" / "clinically recommended" misleading-authority phrasing is gone from generated prose', () => {
  const source = read('lib/academicClinic/reportGenerator.ts')
  assert.doesNotMatch(source, /Clinical recommendation:/)
  assert.doesNotMatch(source, /clinically recommended/)
})

test('Guard D — lib/core/report-cards.ts (the official Report Card domain) still imports zero AI/DeepSeek client', () => {
  const source = read('lib/core/report-cards.ts')
  const importTargets = Array.from(source.matchAll(/from\s+'([^']+)'/g)).map(m => m[1])
  for (const target of importTargets) {
    assert.doesNotMatch(target, /deepseek|\/lib\/ai\//i,
      `lib/core/report-cards.ts imports "${target}" — the official Report Card must remain school-recorded fact, never AI interpretation`)
  }
})

test('Guard E — the parent-facing Report Card page renders the school letterhead component', () => {
  const source = read('app/(parent)/report-card/page.tsx')
  assert.match(source, /SchoolLetterhead/)
})
