import type { LessonPlanRecord } from './types'

function esc(s: string | null | undefined): string {
  if (!s) return ''
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function bullets(items: string[]): string {
  if (!items?.length) return '—'
  return `<ul>${items.map(i => `<li>${esc(i)}</li>`).join('')}</ul>`
}

function nl2p(text: string | null | undefined): string {
  if (!text) return '&nbsp;'
  return esc(text)
    .split('\n')
    .map(l => `<p>${l}</p>`)
    .join('')
}

interface LessonPlanMeta {
  teacherName: string
  tscNumber: string
  school: string
  learningArea: string
  grade: string
  term: string | number
  year: number
}

function buildLessonPlanHTML(plan: LessonPlanRecord, meta: LessonPlanMeta): string {
  return `
  <div class="plan-page">
    <div class="plan-title">LESSON PLAN</div>

    <table class="header-table">
      <tr>
        <td class="header-cell"><span class="header-label">SCHOOL</span><span class="header-value">${esc(meta.school)}</span></td>
        <td class="header-cell"><span class="header-label">GRADE</span><span class="header-value">${esc(meta.grade)}</span></td>
        <td class="header-cell"><span class="header-label">SUBJECT</span><span class="header-value">${esc(meta.learningArea)}</span></td>
        <td class="header-cell"><span class="header-label">DATE</span><span class="header-value">${esc(plan.taught_date || '')}&nbsp;</span></td>
        <td class="header-cell"><span class="header-label">TIME</span><span class="header-value">&nbsp;</span></td>
        <td class="header-cell"><span class="header-label">ROLL</span><span class="header-value">&nbsp;</span></td>
      </tr>
    </table>

    <table class="meta-table">
      <tr>
        <td class="meta-label">Strand:</td>
        <td class="meta-value">${esc(plan.strand)}</td>
        <td class="meta-label">Week / Lesson:</td>
        <td class="meta-value">Week ${plan.week_number}, Lesson ${plan.lesson_number}</td>
      </tr>
      <tr>
        <td class="meta-label">Sub-strand:</td>
        <td class="meta-value" colspan="3">${esc(plan.sub_strand)}</td>
      </tr>
    </table>

    <div class="section">
      <div class="section-title">Specific Learning Outcomes</div>
      <div class="section-body">
        <p class="section-intro">By the end of the lesson, the learner should be able to:</p>
        ${bullets(plan.learning_outcomes as string[])}
      </div>
    </div>

    <div class="section">
      <div class="section-title">Key Inquiry Questions</div>
      <div class="section-body">
        <ol>${(plan.key_inquiry_questions as string[]).map(q => `<li>${esc(q)}</li>`).join('')}</ol>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Teaching / Learning Resources</div>
      <div class="section-body">
        ${bullets(plan.learning_resources as string[])}
      </div>
    </div>

    <div class="section">
      <div class="section-title">Organisation of Learning</div>
      <div class="section-body">${nl2p(plan.organisation_of_learning)}</div>
    </div>

    <div class="section">
      <div class="section-title">Introduction / Getting Started (5 mins)</div>
      <div class="section-body">${nl2p(plan.introduction)}</div>
    </div>

    <div class="section">
      <div class="section-title">Lesson Development</div>
      <div class="section-body">
        <div class="step"><span class="step-label">Step 1 (10 mins):</span> ${nl2p(plan.step_1)}</div>
        <div class="step"><span class="step-label">Step 2 (10 mins):</span> ${nl2p(plan.step_2)}</div>
        <div class="step"><span class="step-label">Step 3 (10 mins):</span> ${nl2p(plan.step_3)}</div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Conclusion / Hitimisho (5 mins)</div>
      <div class="section-body">${nl2p(plan.conclusion)}</div>
    </div>

    <div class="section">
      <div class="section-title">Extended Activities</div>
      <div class="section-body">${nl2p(plan.extended_activities)}</div>
    </div>

    <div class="section reflection-section">
      <div class="section-title">Reflection of the Lesson / Maoni</div>
      <div class="section-body reflection-body">
        ${nl2p(plan.reflection)}
        <div class="reflection-lines">
          <div class="reflection-line"></div>
          <div class="reflection-line"></div>
          <div class="reflection-line"></div>
        </div>
      </div>
    </div>

    <div class="plan-footer">
      <span>${esc(meta.teacherName)} &nbsp;|&nbsp; TSC No: ${esc(meta.tscNumber)} &nbsp;|&nbsp; Term ${meta.term} ${meta.year}</span>
      <span>Generated by EduNexus AI · KICD Aligned</span>
    </div>
  </div>`
}

export function generateLessonPlanHTML(
  plans: LessonPlanRecord[],
  meta: LessonPlanMeta
): string {
  const pages = plans
    .map((plan, i) => {
      const page = buildLessonPlanHTML(plan, meta)
      return i < plans.length - 1
        ? page + '<div class="page-break"></div>'
        : page
    })
    .join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Lesson Plan — ${esc(meta.learningArea)} ${esc(meta.grade)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; font-size: 10pt; color: #000; background: #fff; }

    .page-break { page-break-after: always; break-after: page; }

    .plan-page { padding: 12mm 14mm; max-width: 210mm; }

    .plan-title {
      text-align: center;
      font-size: 16pt;
      font-weight: bold;
      letter-spacing: 3px;
      color: #1e3a5f;
      border-bottom: 3px solid #1e3a5f;
      padding-bottom: 6px;
      margin-bottom: 10px;
    }

    .header-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 8px;
    }
    .header-cell {
      border: 1px solid #999;
      padding: 4px 6px;
      text-align: left;
    }
    .header-label {
      display: block;
      font-size: 7pt;
      font-weight: bold;
      color: #555;
      text-transform: uppercase;
    }
    .header-value {
      display: block;
      font-size: 9.5pt;
      font-weight: bold;
      min-height: 16px;
    }

    .meta-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 10px;
    }
    .meta-label {
      font-weight: bold;
      font-size: 9pt;
      padding: 4px 8px 4px 0;
      width: 18%;
      white-space: nowrap;
    }
    .meta-value {
      font-size: 9.5pt;
      padding: 4px;
      border-bottom: 1px solid #ccc;
    }

    .section {
      margin-bottom: 8px;
      border: 1px solid #ddd;
      border-radius: 2px;
    }
    .section-title {
      background: #1e3a5f;
      color: #fff;
      font-size: 9pt;
      font-weight: bold;
      padding: 4px 8px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .section-body {
      padding: 6px 10px;
      font-size: 9.5pt;
      line-height: 1.5;
    }
    .section-body p { margin: 2px 0; }
    .section-intro { font-style: italic; margin-bottom: 4px; color: #444; }
    ul, ol { margin: 0; padding-left: 18px; }
    ul li, ol li { margin-bottom: 2px; }

    .step { margin-bottom: 6px; }
    .step-label { font-weight: bold; }

    .reflection-section .section-title { background: #374151; }
    .reflection-body { min-height: 40px; }
    .reflection-lines { margin-top: 6px; }
    .reflection-line {
      border-bottom: 1px solid #aaa;
      height: 20px;
      margin-bottom: 4px;
    }

    .plan-footer {
      margin-top: 10px;
      padding-top: 6px;
      border-top: 1px solid #ccc;
      display: flex;
      justify-content: space-between;
      font-size: 7.5pt;
      color: #666;
    }

    @media print {
      .no-print { display: none !important; }
      @page {
        size: A4 portrait;
        margin: 8mm;
      }
    }
  </style>
</head>
<body>
  <div class="no-print" style="text-align:right;padding:12px 16px;">
    <button onclick="window.print()"
      style="background:#1e3a5f;color:#fff;border:none;padding:10px 22px;border-radius:6px;
             font-size:10pt;cursor:pointer;font-weight:bold;">
      Print / Save as PDF
    </button>
  </div>
  ${pages}
</body>
</html>`
}

export function downloadLessonPlanPDF(
  plans: LessonPlanRecord[],
  meta: LessonPlanMeta
): void {
  const html = generateLessonPlanHTML(plans, meta)
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => {
    win.print()
    win.close()
  }, 800)
}
