// lib/sow/pdfRenderer.ts
// HTML → browser print renderer for SOW download.
// Produces: Page 1 = cover page, Page 2+ = A4 landscape SOW table.

import type { SOWPreviewData, GeneratedLesson, BreakItem, CurriculumMode } from './types'

export interface ColConfig {
  col3: string
  col4: string
  col5: string
  col6: string
  col7?: string
  col8: string
  col9: string
  col10?: string
  hasInquiryQuestions: boolean
}

export function getColumnConfig(mode: CurriculumMode): ColConfig {
  if (mode === '844_form3' || mode === '844_form4') {
    return {
      col3: 'TOPIC',
      col4: 'SUB-TOPIC',
      col5: 'OBJECTIVES',
      col6: 'T/L ACTIVITIES',
      col8: 'T/L AIDS',
      col9: 'REFERENCE',
      col10: 'REMARKS',
      hasInquiryQuestions: false,
    }
  }
  return {
    col3: 'STRAND',
    col4: 'SUB-STRAND',
    col5: 'LESSON LEARNING OUTCOMES',
    col6: 'LEARNING EXPERIENCES',
    col7: 'KEY INQUIRY QUESTIONS',
    col8: 'LEARNING RESOURCES',
    col9: 'ASSESSMENT METHODS',
    col10: 'REFLECTION',
    hasInquiryQuestions: true,
  }
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function bullets(items: string[]): string {
  if (!items?.length) return '—'
  return `<ul>${items.map(i => `<li>${esc(i)}</li>`).join('')}</ul>`
}

function breakDetail(b: BreakItem): string {
  const wk = b.startWeek === b.endWeek
    ? `Wk ${b.startWeek}`
    : `Wk ${b.startWeek}–${b.endWeek}`
  return `${wk} · L${b.startLesson}–L${b.endLesson}`
}

function buildCoverPage(meta: SOWPreviewData['meta']): string {
  return `
  <div class="cover-page">
    <div class="cover-govt">REPUBLIC OF KENYA</div>
    <div class="cover-ministry">MINISTRY OF EDUCATION</div>
    <div class="cover-rule"></div>
    <div class="cover-title">SCHEME OF WORK</div>
    <div class="cover-rule"></div>

    <table class="cover-table">
      <tr><td class="cover-label">Teacher Name</td><td class="cover-value">${esc(meta.teacherName || '—')}</td></tr>
      <tr><td class="cover-label">TSC No.</td><td class="cover-value">${esc(meta.tscNumber || '—')}</td></tr>
      <tr><td class="cover-label">School</td><td class="cover-value">${esc(meta.school)}</td></tr>
      <tr><td class="cover-label">Learning Area / Subject</td><td class="cover-value">${esc(meta.learningArea)}</td></tr>
      <tr><td class="cover-label">Grade</td><td class="cover-value">${esc(meta.grade)}</td></tr>
      <tr><td class="cover-label">Term</td><td class="cover-value">Term ${esc(meta.term)}</td></tr>
      <tr><td class="cover-label">Year</td><td class="cover-value">${meta.year}</td></tr>
    </table>

    ${meta.textbook ? `
    <div class="cover-books">
      <div class="cover-books-label">Reference Books Used:</div>
      ${meta.textbook.split(' | ').map(b => `<div class="cover-books-item">• ${esc(b.trim())}</div>`).join('')}
    </div>` : ''}

    <div class="cover-footer">
      Generated by EduNexus · KICD Aligned · ${esc(meta.generatedDate)}
    </div>
  </div>
  <div class="page-break"></div>`
}

function buildTablePage(
  lessons: GeneratedLesson[],
  breaks: BreakItem[],
  meta: SOWPreviewData['meta'],
  colConfig: ColConfig
): string {
  const isCBC = colConfig.hasInquiryQuestions

  // Build a merged timeline: lessons interleaved with one row per BreakItem
  type TableRow =
    | { kind: 'lesson'; lesson: GeneratedLesson }
    | { kind: 'break'; week: number; title: string; detail: string }

  const rows: TableRow[] = []

  const sortedBreaks = [...breaks].sort((a, b) =>
    a.startWeek !== b.startWeek ? a.startWeek - b.startWeek : a.startLesson - b.startLesson
  )
  let bi = 0

  for (const lesson of lessons) {
    // Inject any breaks whose end week falls before this lesson's week
    while (bi < sortedBreaks.length && sortedBreaks[bi].endWeek < lesson.week) {
      const b = sortedBreaks[bi++]
      rows.push({ kind: 'break', week: b.startWeek, title: b.title, detail: breakDetail(b) })
    }
    rows.push({ kind: 'lesson', lesson })
  }

  // Inject any breaks that come after the last lesson
  while (bi < sortedBreaks.length) {
    const b = sortedBreaks[bi++]
    rows.push({ kind: 'break', week: b.startWeek, title: b.title, detail: breakDetail(b) })
  }

  const headerCols = isCBC
    ? `<th style="width:4%">WK</th>
       <th style="width:4%">LSN</th>
       <th style="width:9%">${colConfig.col3}</th>
       <th style="width:11%">${colConfig.col4}</th>
       <th style="width:16%">${colConfig.col5}</th>
       <th style="width:16%">${colConfig.col6}</th>
       <th style="width:12%">${colConfig.col7 || ''}</th>
       <th style="width:10%">${colConfig.col8}</th>
       <th style="width:10%">${colConfig.col9}</th>
       <th style="width:8%">${colConfig.col10 || 'REFLECTION'}</th>`
    : `<th style="width:4%">WK</th>
       <th style="width:4%">LSN</th>
       <th style="width:10%">${colConfig.col3}</th>
       <th style="width:12%">${colConfig.col4}</th>
       <th style="width:18%">${colConfig.col5}</th>
       <th style="width:20%">${colConfig.col6}</th>
       <th style="width:12%">${colConfig.col8}</th>
       <th style="width:12%">${colConfig.col9}</th>
       <th style="width:8%">${colConfig.col10 || 'REMARKS'}</th>`

  const numCols = isCBC ? 10 : 9

  // Pre-compute rowspans for STRAND and SUB-STRAND columns.
  // skipStrand[i]=true means this cell is absorbed by a rowspan above — omit it.
  // strandSpan[i]  = rowspan value for the first cell in a run (1 if no merge needed).
  const skipStrand: boolean[]    = new Array(rows.length).fill(false)
  const strandSpan: number[]     = new Array(rows.length).fill(1)
  const skipSubstrand: boolean[] = new Array(rows.length).fill(false)
  const substrandSpan: number[]  = new Array(rows.length).fill(1)

  for (let ri = 0; ri < rows.length; ri++) {
    const row = rows[ri]
    if (row.kind !== 'lesson' || skipStrand[ri]) continue

    // Strand run
    const strandName = row.lesson.strand
    let sj = ri + 1
    while (sj < rows.length) {
      const next = rows[sj]
      if (next.kind !== 'lesson' || next.lesson.strand !== strandName) break
      skipStrand[sj] = true
      sj++
    }
    strandSpan[ri] = sj - ri

    // Substrand run (always a sub-range of the strand run)
    const substrandName = row.lesson.substrand
    let sk = ri + 1
    while (sk < rows.length) {
      const next = rows[sk]
      if (next.kind !== 'lesson' || next.lesson.substrand !== substrandName) break
      skipSubstrand[sk] = true
      sk++
    }
    substrandSpan[ri] = sk - ri
  }

  const bodyRows = rows.map((row, ri) => {
    if (row.kind === 'break') {
      return `<tr class="break-row">
        <td class="center" style="white-space:nowrap;">${row.week}</td>
        <td class="center">—</td>
        <td colspan="${numCols - 2}" style="padding:5px 8px;">
          <span class="break-badge">BREAK</span>
          <strong style="color:#633806;margin-left:5px;">${esc(row.title)}</strong>
          <span style="color:#854F0B;font-size:6.5pt;margin-left:6px;">${esc(row.detail)}</span>
        </td>
      </tr>`
    }

    const l = row.lesson

    const spanAttr = (span: number) => span > 1 ? ` rowspan="${span}" class="merged-cell"` : ''
    const strandCell    = skipStrand[ri]    ? '' : `<td${spanAttr(strandSpan[ri])}>${esc(l.strand)}</td>`
    const substrandCell = skipSubstrand[ri] ? '' : `<td${spanAttr(substrandSpan[ri])}>${esc(l.substrand)}</td>`

    return isCBC
      ? `<tr>
          <td class="center">${l.week}</td>
          <td class="center">${l.lesson}</td>
          ${strandCell}
          ${substrandCell}
          <td>${bullets(l.learningOutcomes)}</td>
          <td>${bullets(l.learningExperiences)}</td>
          <td>${bullets(l.keyInquiryQuestions)}</td>
          <td>${bullets(l.learningResources)}</td>
          <td>${bullets(l.assessmentMethods)}</td>
          <td class="reflection-cell">${esc(l.reflection || '')}</td>
        </tr>`
      : `<tr>
          <td class="center">${l.week}</td>
          <td class="center">${l.lesson}</td>
          ${strandCell}
          ${substrandCell}
          <td>${bullets(l.learningOutcomes)}</td>
          <td>${bullets(l.learningExperiences)}</td>
          <td>${bullets(l.learningResources)}</td>
          <td>${bullets(l.assessmentMethods)}</td>
          <td class="reflection-cell">${esc(l.reflection || '')}</td>
        </tr>`
  }).join('')

  return `
  <div class="sow-page">
    <div class="sow-header">
      <strong>${esc(meta.school)}</strong> &nbsp;|&nbsp;
      ${esc(meta.learningArea)} &nbsp;|&nbsp;
      ${esc(meta.grade)} &nbsp;|&nbsp;
      Term ${esc(meta.term)} ${meta.year}
    </div>
    <table>
      <thead>
        <tr>${headerCols}</tr>
      </thead>
      <tbody>
        ${bodyRows}
      </tbody>
    </table>
    <div class="sow-footer">
      Total Lessons: <strong>${meta.totalLessons}</strong> &nbsp;·&nbsp;
      Quality: <strong>${Math.round(meta.averageConfidence * 100)}%</strong> &nbsp;·&nbsp;
      KICD Aligned · EduNexus · ${esc(meta.generatedDate)}
    </div>
  </div>`
}

export function generateSOWHTML(
  data: SOWPreviewData,
  colConfig: ColConfig
): string {
  const { meta, lessons, breaks } = data

  const cover = buildCoverPage(meta)
  const table = buildTablePage(lessons, breaks, meta, colConfig)

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>SOW — ${esc(meta.learningArea)} ${esc(meta.grade)} Term ${esc(meta.term)} ${meta.year}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; font-size: 9pt; color: #000; background: #fff; }

    /* ── Cover page ─────────────────────────────────────────── */
    .cover-page {
      width: 180mm;
      margin: 40mm auto;
      text-align: center;
      padding: 20mm;
      border: 2px solid #1e3a5f;
    }
    .cover-govt   { font-size: 13pt; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; }
    .cover-ministry { font-size: 10pt; margin-top: 4px; }
    .cover-rule   { border-top: 2px solid #1e3a5f; margin: 12px 0; }
    .cover-title  { font-size: 18pt; font-weight: bold; letter-spacing: 3px; margin: 8px 0; }
    .cover-table  { width: 100%; margin: 20px 0; border-collapse: collapse; text-align: left; }
    .cover-label  { width: 45%; padding: 6px 8px; font-weight: bold; font-size: 9pt; border-bottom: 1px solid #ddd; }
    .cover-value  { padding: 6px 8px; font-size: 9pt; border-bottom: 1px solid #ddd; }
    .cover-books  { text-align: left; margin-top: 12px; font-size: 9pt; }
    .cover-books-label { font-weight: bold; margin-bottom: 4px; }
    .cover-books-item  { margin-left: 8px; }
    .cover-footer { margin-top: 24px; font-size: 7.5pt; color: #666; }

    /* ── Page break ─────────────────────────────────────────── */
    .page-break { page-break-after: always; break-after: page; }

    /* ── SOW table page ─────────────────────────────────────── */
    .sow-page { padding: 8mm; }
    .sow-header {
      font-size: 8pt;
      text-align: center;
      margin-bottom: 6px;
      color: #1e3a5f;
    }
    table {
      width: 100%;
      border-collapse: collapse;
    }
    thead tr {
      background: #1e3a5f;
      color: #fff;
    }
    th {
      font-size: 7pt;
      padding: 5px 3px;
      text-align: left;
      border: 1px solid #999;
      font-weight: bold;
      text-transform: uppercase;
    }
    td {
      font-size: 7.5pt;
      padding: 4px 3px;
      border: 1px solid #ccc;
      vertical-align: top;
    }
    tr:nth-child(even) td { background: #f8f9ff; }
    .center { text-align: center; }
    ul { margin: 0; padding-left: 12px; }
    ul li { margin-bottom: 2px; }
    .reflection-cell { color: #555; font-style: italic; }

    /* ── Merged strand/substrand cells ─────────────────────── */
    .merged-cell {
      vertical-align: middle;
      background: #eef2ff !important;
      font-weight: bold;
      border-right: 2px solid #6366f1;
    }

    /* ── Break rows ─────────────────────────────────────────── */
    .break-row td { background: #FAEEDA !important; color: #92400e; border-color: #EF9F2766 !important; }
    .break-badge {
      font-size: 6.5pt;
      padding: 1px 5px;
      border-radius: 8px;
      background: #FAC775;
      color: #633806;
      font-weight: bold;
      white-space: nowrap;
    }

    /* ── Footer ─────────────────────────────────────────────── */
    .sow-footer {
      margin-top: 8px;
      font-size: 7.5pt;
      color: #555;
      border-top: 1px solid #ccc;
      padding-top: 6px;
      text-align: right;
    }

    /* ── Print ──────────────────────────────────────────────── */
    @media print {
      .no-print { display: none !important; }
      @page {
        size: A4 landscape;
        margin: 10mm;
      }
      .cover-page { border: 2px solid #1e3a5f; }
    }
  </style>
</head>
<body>
  <div class="no-print" style="text-align:right;padding:12px 16px;">
    <button onclick="window.print()"
      style="background:#1e3a5f;color:#fff;border:none;padding:10px 22px;border-radius:6px;
             font-size:10pt;cursor:pointer;font-weight:bold;">
      Print / Save as PDF
    </button>
  </div>
  ${cover}
  ${table}
</body>
</html>`
}

export function downloadSOWAsPDF(data: SOWPreviewData, colConfig: ColConfig): void {
  const html = generateSOWHTML(data, colConfig)
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => {
    win.print()
    win.close()
  }, 800)
}
