// POST /api/teacher/classes/[classId]/differentiation/approve
//
// Teacher approval gate (Adaptive Learning v2 Architecture §3/§9) — nothing
// generated by /differentiation reaches a learner (print or share) until
// this is called. `adjustedGroups`, when present, is what gets persisted —
// an adjusted plan is never silently reverted to the AI's original
// proposal. Same interaction shape as /api/holiday/publish.

import { z } from 'zod'
import { createClient } from '@/utils/supabase/server'
import { createServiceClient } from '@/utils/supabase/service'
import { apiSuccess, apiError, apiUnauthorized, apiForbidden, apiBadRequest } from '@/lib/api/response'
import { approveClassDifferentiation } from '@/lib/adaptiveLearning/differentiation'
import type { ClassGroups } from '@/lib/adaptiveLearning/recommend'

const AdaptiveTaskSchema = z.object({
  observation: z.string(),
  evidence:    z.array(z.string()),
  confidence:  z.enum(['Low', 'Medium', 'High']),
  action:      z.string(),
  learnerId:   z.string(),
  subject:     z.string(),
  groupType:   z.enum(['critical_gap', 'prerequisite_gap', 'concept_confusion', 'on_track', 'insufficient_data']),
  level:       z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.null()]),
  taskStyle:   z.enum(['foundational', 'reinforcement', 'application', 'enrichment']),
})

const BodySchema = z.object({
  subject: z.string().min(1),
  term:    z.number().int().min(1).max(3),
  year:    z.number().int().min(2024),
  adjustedGroups: z.object({
    critical_gap:      z.array(AdaptiveTaskSchema),
    prerequisite_gap:  z.array(AdaptiveTaskSchema),
    concept_confusion: z.array(AdaptiveTaskSchema),
    on_track:          z.array(AdaptiveTaskSchema),
    insufficient_data: z.array(AdaptiveTaskSchema),
  }).optional(),
})

export async function POST(req: Request, { params }: { params: Promise<{ classId: string }> }): Promise<Response> {
  try {
    const { classId } = await params
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return apiUnauthorized()

    const db = createServiceClient()
    const { data: teacher } = await db.from('teachers').select('id').eq('user_id', user.id).single()
    if (!teacher) return apiForbidden()

    const { data: cls } = await db
      .from('teacher_classes')
      .select('id')
      .eq('id', classId)
      .eq('teacher_id', teacher.id)
      .maybeSingle()
    if (!cls) return apiForbidden()

    const parsed = BodySchema.safeParse(await req.json())
    if (!parsed.success) return apiBadRequest(parsed.error.issues[0]?.message ?? 'Invalid input')

    const published = await approveClassDifferentiation({
      classId, teacherId: teacher.id, subject: parsed.data.subject,
      term: parsed.data.term, year: parsed.data.year,
      adjustedGroups: parsed.data.adjustedGroups as ClassGroups | undefined,
    })
    if (published === 0) return apiForbidden()

    return apiSuccess({ published })
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e)
    console.error('[teacher/classes/differentiation/approve]', msg)
    return apiError('Failed to approve class differentiation')
  }
}
