// lib/row/pdfRenderer.ts
// HTML → browser print renderer for Record of Work download.
// Produces: Page 1 = cover page, Page 2+ = A4 landscape ROW table.
// Mirrors lib/sow/pdfRenderer.ts exactly in structure and CSS variables.

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ROWEntry {
  week_number:           number
  lesson_number:         number
  strand:                string
  sub_strand:            string
  learning_outcomes:     string | string[]
  key_inquiry_questions: string | string[]
  learning_resources:    string | string[]
  activities_summary:    string | string[]
  status:                'completed' | 'not_completed' | 'carried_forward'
  remarks:               string
}

export interface RecordOfWork {
  teacher_name: string
  tsc_number:   string
  school:       string
  grade:        string
  learning_area: string
  term:         number | string
  year:         number | string
  entries:      ROWEntry[]
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function esc(s: string | number | undefined | null): string {
  if (s == null) return '—'
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function bullets(value: string | string[] | undefined | null): string {
  if (!value) return '—'
  const items = Array.isArray(value) ? value : [value]
  if (!items.length) return '—'
  return `<ul>${items.map(i => `<li>${esc(i)}</li>`).join('')}</ul>`
}

// Term start dates: [month (0-based), day]
const TERM_STARTS: Record<string, [number, number]> = {
  '1': [0, 6],  // Jan 6
  '2': [4, 5],  // May 5
  '3': [8, 1],  // Sep 1
}

function getLessonDate(
  weekNumber: number,
  term: number | string,
  year: number | string
): string {
  const start = TERM_STARTS[String(term)]
  if (!start) return `Wk ${weekNumber}`
  const base = new Date(Number(year), start[0], start[1])
  base.setDate(base.getDate() + (weekNumber - 1) * 7)
  return base.toLocaleDateString('en-KE', { day: 'numeric', month: 'short' })
}

function statusClass(status: ROWEntry['status']): string {
  if (status === 'not_completed')  return 'row-not-completed'
  if (status === 'carried_forward') return 'row-carried'
  return ''
}

// ─── Cover page ───────────────────────────────────────────────────────────────

function buildCoverPage(row: RecordOfWork): string {
  const today = new Date().toLocaleDateString('en-KE', {
    day: 'numeric', month: 'long', year: 'numeric',
  })

  return `
  <div class="cover-page">
    <div class="cover-govt">REPUBLIC OF KENYA</div>
    <div class="cover-ministry">MINISTRY OF EDUCATION</div>
    <div class="cover-rule"></div>
    <div class="cover-title">RECORD OF WORK COVERED</div>
    <div class="cover-rule"></div>

    <table class="cover-table">
      <tr><td class="cover-label">Teacher Name</td>          <td class="cover-value">${esc(row.teacher_name)}</td></tr>
      <tr><td class="cover-label">TSC No.</td>               <td class="cover-value">${esc(row.tsc_number)}</td></tr>
      <tr><td class="cover-label">School</td>                <td class="cover-value">${esc(row.school)}</td></tr>
      <tr><td class="cover-label">Learning Area / Subject</td><td class="cover-value">${esc(row.learning_area)}</td></tr>
      <tr><td class="cover-label">Grade</td>                 <td class="cover-value">${esc(row.grade)}</td></tr>
      <tr><td class="cover-label">Term</td>                  <td class="cover-value">Term ${esc(row.term)}</td></tr>
      <tr><td class="cover-label">Year</td>                  <td class="cover-value">${esc(row.year)}</td></tr>
    </table>

    <div class="cover-footer">
      Generated by EduNexus AI · KICD Aligned · ${today}
    </div>
  </div>
  <div class="page-break"></div>`
}

// ─── Table page ───────────────────────────────────────────────────────────────

function buildTablePage(row: RecordOfWork): string {
  const entries = row.entries
  const n = entries.length

  // Pre-compute rowspans for STRAND and SUB-STRAND columns.
  // skipX[i] = true → this cell is absorbed by a rowspan above, omit it.
  const skipStrand:    boolean[] = new Array(n).fill(false)
  const strandSpan:    number[]  = new Array(n).fill(1)
  const skipSubstrand: boolean[] = new Array(n).fill(false)
  const substrandSpan: number[]  = new Array(n).fill(1)

  for (let i = 0; i < n; i++) {
    if (skipStrand[i]) continue

    // Strand run
    const strandName = entries[i].strand
    let sj = i + 1
    while (sj < n && entries[sj].strand === strandName) { skipStrand[sj] = true; sj++ }
    strandSpan[i] = sj - i

    // Sub-strand run (always a sub-range of the strand run)
    const subName = entries[i].sub_strand
    let sk = i + 1
    while (
      sk < n &&
      entries[sk].sub_strand === subName &&
      entries[sk].strand === strandName
    ) { skipSubstrand[sk] = true; sk++ }
    substrandSpan[i] = sk - i
  }

  const spanAttr = (span: number) =>
    span > 1 ? ` rowspan="${span}" class="merged-cell"` : ''

  const bodyRows = entries.map((e, i) => {
    const date          = getLessonDate(e.week_number, row.term, row.year)
    const strandCell    = skipStrand[i]    ? '' : `<td${spanAttr(strandSpan[i])}>${esc(e.strand)}</td>`
    const substrandCell = skipSubstrand[i] ? '' : `<td${spanAttr(substrandSpan[i])}>${esc(e.sub_strand)}</td>`

    return `<tr class="${statusClass(e.status)}">
      <td class="center">${e.week_number}</td>
      <td class="center">${e.lesson_number}</td>
      <td class="center date-cell">${esc(date)}</td>
      ${strandCell}
      ${substrandCell}
      <td>${bullets(e.learning_outcomes)}</td>
      <td>${bullets(e.key_inquiry_questions)}</td>
      <td>${bullets(e.activities_summary)}</td>
      <td>${bullets(e.learning_resources)}</td>
      <td class="center assess-cell">—</td>
      <td class="remarks-cell">${esc(e.remarks)}</td>
      <td class="sig-cell"></td>
    </tr>`
  }).join('')

  // Footer counts
  const total     = n
  const completed = entries.filter(e => e.status === 'completed').length
  const carried   = entries.filter(e => e.status === 'carried_forward').length

  return `
  <div class="sow-page">
    <div class="sow-header">
      <strong>${esc(row.school)}</strong> &nbsp;|&nbsp;
      ${esc(row.learning_area)} &nbsp;|&nbsp;
      ${esc(row.grade)} &nbsp;|&nbsp;
      Term ${esc(row.term)} ${esc(row.year)} &nbsp;|&nbsp;
      ${esc(row.teacher_name)}
    </div>
    <table>
      <thead>
        <tr>
          <th style="width:3%">WK</th>
          <th style="width:3%">LSN</th>
          <th style="width:6%">DATE</th>
          <th style="width:8%">STRAND</th>
          <th style="width:9%">SUB-STRAND</th>
          <th style="width:12%">LEARNING OUTCOMES</th>
          <th style="width:11%">KEY INQUIRY QUESTIONS</th>
          <th style="width:14%">LEARNING EXPERIENCES / ACTIVITIES</th>
          <th style="width:10%">LEARNING RESOURCES</th>
          <th style="width:7%">ASSESSMENT</th>
          <th style="width:10%">REMARKS / REFLECTION</th>
          <th style="width:7%">SIGNATURE</th>
        </tr>
      </thead>
      <tbody>
        ${bodyRows}
      </tbody>
    </table>
    <div class="sow-footer">
      Total Lessons: <strong>${total}</strong> &nbsp;|&nbsp;
      Completed: <strong>${completed}</strong> &nbsp;|&nbsp;
      Carried Forward: <strong>${carried}</strong>
      &nbsp;·&nbsp; EduNexus · KICD Aligned
    </div>
  </div>`
}

// ─── CSS (shared with sow/pdfRenderer — same variables) ──────────────────────

const CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; font-size: 9pt; color: #000; background: #fff; }

  /* ── Cover page ─────────────────────────────────────────── */
  .cover-page {
    width: 180mm;
    margin: 40mm auto;
    text-align: center;
    padding: 20mm;
    border: 2px solid #1e3a5f;
  }
  .cover-govt     { font-size: 13pt; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; }
  .cover-ministry { font-size: 10pt; margin-top: 4px; }
  .cover-rule     { border-top: 2px solid #1e3a5f; margin: 12px 0; }
  .cover-title    { font-size: 18pt; font-weight: bold; letter-spacing: 3px; margin: 8px 0; }
  .cover-table    { width: 100%; margin: 20px 0; border-collapse: collapse; text-align: left; }
  .cover-label    { width: 45%; padding: 6px 8px; font-weight: bold; font-size: 9pt; border-bottom: 1px solid #ddd; }
  .cover-value    { padding: 6px 8px; font-size: 9pt; border-bottom: 1px solid #ddd; }
  .cover-footer   { margin-top: 24px; font-size: 7.5pt; color: #666; }

  /* ── Page break ─────────────────────────────────────────── */
  .page-break { page-break-after: always; break-after: page; }

  /* ── ROW table page ─────────────────────────────────────── */
  .sow-page { padding: 8mm; }
  .sow-header {
    font-size: 8pt;
    text-align: center;
    margin-bottom: 6px;
    color: #1e3a5f;
  }
  table { width: 100%; border-collapse: collapse; }
  thead tr { background: #1e3a5f; color: #fff; }
  th {
    font-size: 6.5pt;
    padding: 5px 3px;
    text-align: left;
    border: 1px solid #999;
    font-weight: bold;
    text-transform: uppercase;
  }
  td {
    font-size: 7.5pt;
    padding: 4px 3px;
    border: 1px solid #ccc;
    vertical-align: top;
  }
  tr:nth-child(even) td { background: #f8f9ff; }
  .center    { text-align: center; }
  .date-cell { font-size: 7pt; color: #444; white-space: nowrap; }
  ul { margin: 0; padding-left: 12px; }
  ul li { margin-bottom: 2px; }
  .remarks-cell { color: #555; font-style: italic; }
  .assess-cell  { color: #888; }
  .sig-cell     { background: #fafafa !important; }

  /* ── Merged strand/substrand cells ─────────────────────── */
  .merged-cell {
    vertical-align: middle;
    background: #eef2ff !important;
    font-weight: bold;
    border-right: 2px solid #6366f1;
  }

  /* ── Status row colors (override alternating bg) ────────── */
  tr.row-not-completed td  { background: #fff0f0 !important; }
  tr.row-carried td        { background: #fef3c7 !important; }

  /* ── Footer ─────────────────────────────────────────────── */
  .sow-footer {
    margin-top: 8px;
    font-size: 7.5pt;
    color: #555;
    border-top: 1px solid #ccc;
    padding-top: 6px;
    text-align: right;
  }

  /* ── Print ──────────────────────────────────────────────── */
  @media print {
    .no-print { display: none !important; }
    @page { size: A4 landscape; margin: 10mm; }
    .cover-page { border: 2px solid #1e3a5f; }
  }
`

// ─── Public API ───────────────────────────────────────────────────────────────

export function generateROWHTML(row: RecordOfWork): string {
  const cover = buildCoverPage(row)
  const table = buildTablePage(row)

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Record of Work — ${esc(row.learning_area)} ${esc(row.grade)} Term ${esc(row.term)} ${esc(row.year)}</title>
  <style>${CSS}</style>
</head>
<body>
  <div class="no-print" style="text-align:right;padding:12px 16px;">
    <button onclick="window.print()"
      style="background:#1e3a5f;color:#fff;border:none;padding:10px 22px;border-radius:6px;
             font-size:10pt;cursor:pointer;font-weight:bold;">
      Print / Save as PDF
    </button>
  </div>
  ${cover}
  ${table}
</body>
</html>`
}

export function downloadROWAsPDF(row: RecordOfWork): void {
  const html = generateROWHTML(row)
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => {
    win.print()
    win.close()
  }, 800)
}
