// app/api/careers/search/route.ts

import { NextRequest, NextResponse } from 'next/server';
import { findCareerByName, getAllCareerNames } from '@/lib/academicClinic/careerDatabase';
import { generateDynamicCareer } from '@/lib/academicClinic/dynamicCareerGenerator';

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const careerName = searchParams.get('name');
  const autocomplete = searchParams.get('autocomplete');

  try {
    // Autocomplete endpoint
    if (autocomplete === 'true') {
      const allCareers = getAllCareerNames();
      return NextResponse.json({ careers: allCareers });
    }

    // Validate career name
    if (!careerName) {
      return NextResponse.json(
        { error: 'Career name is required' },
        { status: 400 }
      );
    }

    // 1. Try static database first
    const staticCareer = findCareerByName(careerName);

    if (staticCareer) {
      return NextResponse.json({
        career: staticCareer,
        source: 'static',
        message: 'Career from our curated database'
      });
    }

    // 2. Generate dynamically with AI
    try {
      const dynamicCareer = await generateDynamicCareer(careerName);
      
      return NextResponse.json({
        career: dynamicCareer,
        source: 'dynamic',
        message: 'Career generated by AI. Data will be reviewed by our team.'
      });
    } catch (aiError) {
      console.error('AI generation failed:', aiError);
      
      return NextResponse.json(
        { 
          error: 'Failed to generate career information',
          details: aiError instanceof Error ? aiError.message : 'AI generation error'
        },
        { status: 500 }
      );
    }

  } catch (error) {
    console.error('Career search error:', error);
    
    return NextResponse.json(
      { 
        error: 'Search failed',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

// Edge runtime config (optional but recommended)
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';