// lib/slides/pptxBuilder.ts
// Builds a styled .pptx file from AI-generated slide content using pptxgenjs.

import PptxGenJS from 'pptxgenjs'
import type { GeneratedSlides, SlideContent } from './aiSlideGenerator'

// ─── Brand palette ────────────────────────────────────────────────────────────
const COLOR = {
  navy:       '0C1929',
  blue:       '2563EB',
  lightBlue:  '3B82F6',
  cyan:       '06B6D4',
  white:      'FFFFFF',
  offWhite:   'F1F5F9',
  slate:      '64748B',
  dark:       '1E293B',
  amber:      'F59E0B',
  green:      '10B981',
  bullet:     '1D4ED8',
} as const

const FONT = {
  heading: 'Calibri',
  body:    'Calibri',
} as const

// ─── Helpers ──────────────────────────────────────────────────────────────────

function addBackground(slide: PptxGenJS.Slide, dark: boolean) {
  slide.background = { color: dark ? COLOR.navy : COLOR.white }
}

function addHeaderBar(slide: PptxGenJS.Slide, title: string, accent: string = COLOR.blue) {
  // Colored top bar
  slide.addShape('rect', {
    x: 0, y: 0, w: '100%', h: 0.75,
    fill: { color: accent },
    line: { color: accent, width: 0 },
  })
  // Slide title in bar
  slide.addText(title, {
    x: 0.3, y: 0, w: 8.5, h: 0.75,
    fontSize: 20, bold: true,
    color: COLOR.white,
    fontFace: FONT.heading,
    valign: 'middle',
  })
  // EduNexus brand mark (right side of bar)
  slide.addText('EduNexus', {
    x: 8.8, y: 0, w: 1.1, h: 0.75,
    fontSize: 9, bold: true,
    color: COLOR.white,
    fontFace: FONT.heading,
    valign: 'middle',
    align: 'right',
  })
}

function addFooter(slide: PptxGenJS.Slide, subject: string, grade: string, dark = false) {
  const textColor = dark ? '475569' : '94A3B8'
  slide.addText(`${subject}  ·  ${grade}`, {
    x: 0.3, y: 7.0, w: 9.4, h: 0.3,
    fontSize: 8,
    color: textColor,
    fontFace: FONT.body,
    align: 'center',
  })
}

// ─── Slide builders ───────────────────────────────────────────────────────────

function buildTitleSlide(
  pptx: PptxGenJS,
  slide: Extract<SlideContent, { type: 'title' }>,
  subject: string,
  grade: string,
) {
  const s = pptx.addSlide()
  addBackground(s, true)

  // Diagonal accent stripe
  s.addShape('rect', {
    x: 0, y: 0, w: '100%', h: 0.08,
    fill: { color: COLOR.lightBlue },
    line: { color: COLOR.lightBlue, width: 0 },
  })
  s.addShape('rect', {
    x: 0, y: 7.42, w: '100%', h: 0.08,
    fill: { color: COLOR.cyan },
    line: { color: COLOR.cyan, width: 0 },
  })

  // Subject + grade pill
  s.addText(`${subject}  ·  ${grade}`, {
    x: 0.5, y: 1.1, w: 9, h: 0.45,
    fontSize: 12, bold: false,
    color: COLOR.cyan,
    fontFace: FONT.body,
    align: 'center',
  })

  // Big topic title
  s.addText(slide.title, {
    x: 0.5, y: 1.8, w: 9, h: 2.4,
    fontSize: 40, bold: true,
    color: COLOR.white,
    fontFace: FONT.heading,
    align: 'center',
    valign: 'middle',
    wrap: true,
  })

  // Subtitle
  s.addText(slide.subtitle, {
    x: 0.5, y: 4.2, w: 9, h: 0.8,
    fontSize: 16,
    color: '94A3B8',
    fontFace: FONT.body,
    align: 'center',
    wrap: true,
  })

  // EduNexus branding bottom
  s.addText('Generated by EduNexus — Kenya CBC AI Platform', {
    x: 0.3, y: 7.1, w: 9.4, h: 0.3,
    fontSize: 8,
    color: '334155',
    fontFace: FONT.body,
    align: 'center',
  })

  s.addNotes(slide.notes)
}

function buildAgendaSlide(
  pptx: PptxGenJS,
  slide: Extract<SlideContent, { type: 'agenda' }>,
  subject: string,
  grade: string,
) {
  const s = pptx.addSlide()
  addBackground(s, false)
  addHeaderBar(s, slide.title, COLOR.navy)

  slide.items.forEach((item, i) => {
    const yPos = 1.1 + i * 0.65

    // Number circle
    s.addShape('ellipse', {
      x: 0.35, y: yPos + 0.08, w: 0.45, h: 0.45,
      fill: { color: COLOR.blue },
      line: { color: COLOR.blue, width: 0 },
    })
    s.addText(String(i + 1), {
      x: 0.35, y: yPos + 0.08, w: 0.45, h: 0.45,
      fontSize: 12, bold: true,
      color: COLOR.white,
      fontFace: FONT.heading,
      align: 'center',
      valign: 'middle',
    })

    // Item text
    s.addText(item, {
      x: 0.9, y: yPos, w: 8.8, h: 0.6,
      fontSize: 15,
      color: COLOR.dark,
      fontFace: FONT.body,
      valign: 'middle',
    })
  })

  addFooter(s, subject, grade)
  s.addNotes(slide.notes)
}

function buildContentSlide(
  pptx: PptxGenJS,
  slide: Extract<SlideContent, { type: 'content' }>,
  subject: string,
  grade: string,
  slideIndex: number,
) {
  const s = pptx.addSlide()
  addBackground(s, false)

  // Alternate accent color slightly for visual variety
  const accent = slideIndex % 2 === 0 ? COLOR.blue : COLOR.navy
  addHeaderBar(s, slide.title, accent)

  // Left accent bar
  s.addShape('rect', {
    x: 0.3, y: 1.0, w: 0.05, h: 5.8,
    fill: { color: COLOR.lightBlue },
    line: { color: COLOR.lightBlue, width: 0 },
  })

  slide.bullets.forEach((bullet, i) => {
    const yPos = 1.05 + i * 0.9
    s.addText('▸', {
      x: 0.5, y: yPos, w: 0.3, h: 0.8,
      fontSize: 13, bold: true,
      color: COLOR.blue,
      fontFace: FONT.body,
      valign: 'middle',
    })
    s.addText(bullet, {
      x: 0.85, y: yPos, w: 8.9, h: 0.8,
      fontSize: 15,
      color: COLOR.dark,
      fontFace: FONT.body,
      valign: 'middle',
      wrap: true,
    })
  })

  if (slide.detail) {
    s.addShape('rect', {
      x: 0.3, y: 6.35, w: 9.4, h: 0.55,
      fill: { color: 'EFF6FF' },
      line: { color: 'BFDBFE', width: 1 },
    })
    s.addText(`💡  ${slide.detail}`, {
      x: 0.4, y: 6.35, w: 9.2, h: 0.55,
      fontSize: 11,
      color: '1D4ED8',
      fontFace: FONT.body,
      valign: 'middle',
      italic: true,
    })
  }

  addFooter(s, subject, grade)
  s.addNotes(slide.notes)
}

function buildActivitySlide(
  pptx: PptxGenJS,
  slide: Extract<SlideContent, { type: 'activity' }>,
  subject: string,
  grade: string,
) {
  const s = pptx.addSlide()
  addBackground(s, false)
  addHeaderBar(s, slide.title, COLOR.amber)

  // Time badge
  s.addShape('rect', {
    x: 8.2, y: 0.85, w: 1.55, h: 0.45,
    fill: { color: 'FEF3C7' },
    line: { color: COLOR.amber, width: 1.5 },
  })
  s.addText(`⏱  ${slide.time_minutes} min`, {
    x: 8.2, y: 0.85, w: 1.55, h: 0.45,
    fontSize: 11, bold: true,
    color: '92400E',
    fontFace: FONT.body,
    align: 'center',
    valign: 'middle',
  })

  // Instructions
  slide.instructions.forEach((step, i) => {
    const yPos = 1.1 + i * 0.85
    // Step badge
    s.addShape('rect', {
      x: 0.3, y: yPos + 0.05, w: 0.55, h: 0.6,
      fill: { color: COLOR.amber },
      line: { color: COLOR.amber, width: 0 },
    })
    s.addText(`Step ${i + 1}`, {
      x: 0.3, y: yPos + 0.05, w: 0.55, h: 0.6,
      fontSize: 9, bold: true,
      color: COLOR.white,
      fontFace: FONT.heading,
      align: 'center',
      valign: 'middle',
    })
    s.addText(step, {
      x: 0.95, y: yPos, w: 8.7, h: 0.75,
      fontSize: 14,
      color: COLOR.dark,
      fontFace: FONT.body,
      valign: 'middle',
      wrap: true,
    })
  })

  addFooter(s, subject, grade)
  s.addNotes(slide.notes)
}

function buildKeyConceptsSlide(
  pptx: PptxGenJS,
  slide: Extract<SlideContent, { type: 'key_concepts' }>,
  subject: string,
  grade: string,
) {
  const s = pptx.addSlide()
  addBackground(s, false)
  addHeaderBar(s, slide.title, COLOR.green)

  const cols = slide.concepts.length <= 3 ? 1 : 2
  slide.concepts.forEach((concept, i) => {
    const col  = cols === 2 ? i % 2 : 0
    const row  = cols === 2 ? Math.floor(i / 2) : i
    const xPos = cols === 2 ? 0.3 + col * 4.9 : 0.3
    const yPos = 1.05 + row * 1.5
    const cardW = cols === 2 ? 4.6 : 9.4

    s.addShape('rect', {
      x: xPos, y: yPos, w: cardW, h: 1.35,
      fill: { color: 'F0FDF4' },
      line: { color: '86EFAC', width: 1 },
    })
    s.addText(concept.term, {
      x: xPos + 0.15, y: yPos + 0.08, w: cardW - 0.3, h: 0.4,
      fontSize: 13, bold: true,
      color: '166534',
      fontFace: FONT.heading,
    })
    s.addText(concept.definition, {
      x: xPos + 0.15, y: yPos + 0.5, w: cardW - 0.3, h: 0.75,
      fontSize: 12,
      color: COLOR.dark,
      fontFace: FONT.body,
      wrap: true,
    })
  })

  addFooter(s, subject, grade)
  s.addNotes(slide.notes)
}

function buildDiscussionSlide(
  pptx: PptxGenJS,
  slide: Extract<SlideContent, { type: 'discussion' }>,
  subject: string,
  grade: string,
) {
  const s = pptx.addSlide()
  addBackground(s, true)
  addHeaderBar(s, slide.title, COLOR.cyan)

  slide.questions.forEach((question, i) => {
    const yPos = 1.1 + i * 1.5

    s.addShape('rect', {
      x: 0.3, y: yPos, w: 9.4, h: 1.3,
      fill: { color: '0F2744' },
      line: { color: '1D4ED8', width: 1 },
    })
    s.addText(`Q${i + 1}`, {
      x: 0.45, y: yPos + 0.1, w: 0.5, h: 1.1,
      fontSize: 20, bold: true,
      color: COLOR.cyan,
      fontFace: FONT.heading,
      valign: 'middle',
    })
    s.addText(question, {
      x: 1.05, y: yPos + 0.05, w: 8.5, h: 1.2,
      fontSize: 14,
      color: COLOR.offWhite,
      fontFace: FONT.body,
      valign: 'middle',
      wrap: true,
    })
  })

  addFooter(s, subject, grade, true)
  s.addNotes(slide.notes)
}

function buildSummarySlide(
  pptx: PptxGenJS,
  slide: Extract<SlideContent, { type: 'summary' }>,
  subject: string,
  grade: string,
) {
  const s = pptx.addSlide()
  addBackground(s, true)

  // Top accent
  s.addShape('rect', {
    x: 0, y: 0, w: '100%', h: 0.08,
    fill: { color: COLOR.green },
    line: { color: COLOR.green, width: 0 },
  })

  s.addText(slide.title, {
    x: 0.4, y: 0.2, w: 9.2, h: 0.7,
    fontSize: 24, bold: true,
    color: COLOR.white,
    fontFace: FONT.heading,
    align: 'center',
  })

  // Key takeaways column
  s.addText('Key Takeaways', {
    x: 0.3, y: 1.05, w: 5.8, h: 0.45,
    fontSize: 13, bold: true,
    color: COLOR.cyan,
    fontFace: FONT.heading,
  })

  slide.key_takeaways.forEach((point, i) => {
    s.addText(`✓  ${point}`, {
      x: 0.3, y: 1.6 + i * 0.75, w: 5.8, h: 0.7,
      fontSize: 13,
      color: COLOR.offWhite,
      fontFace: FONT.body,
      wrap: true,
    })
  })

  // Homework panel
  if (slide.homework) {
    s.addShape('rect', {
      x: 6.4, y: 1.05, w: 3.3, h: 4.2,
      fill: { color: '0F2744' },
      line: { color: COLOR.amber, width: 1.5 },
    })
    s.addText('📚  Homework', {
      x: 6.5, y: 1.15, w: 3.1, h: 0.5,
      fontSize: 13, bold: true,
      color: COLOR.amber,
      fontFace: FONT.heading,
    })
    s.addText(slide.homework, {
      x: 6.5, y: 1.75, w: 3.1, h: 3.3,
      fontSize: 12,
      color: COLOR.offWhite,
      fontFace: FONT.body,
      wrap: true,
      valign: 'top',
    })
  }

  // EduNexus footer
  s.addText('Generated by EduNexus — Kenya CBC AI Platform', {
    x: 0.3, y: 7.1, w: 9.4, h: 0.3,
    fontSize: 8,
    color: '334155',
    fontFace: FONT.body,
    align: 'center',
  })

  s.addNotes(slide.notes)
}

// ─── Main builder ─────────────────────────────────────────────────────────────

export async function buildPptx(data: GeneratedSlides): Promise<Buffer> {
  const pptx = new PptxGenJS()

  pptx.layout  = 'LAYOUT_WIDE'  // 13.33 × 7.5 inches (16:9)
  pptx.author  = 'EduNexus'
  pptx.company = 'EduNexus Kenya'
  pptx.subject = data.topic
  pptx.title   = data.presentation_title

  let contentSlideIndex = 0

  for (const slide of data.slides) {
    switch (slide.type) {
      case 'title':
        buildTitleSlide(pptx, slide, data.subject, data.grade)
        break
      case 'agenda':
        buildAgendaSlide(pptx, slide, data.subject, data.grade)
        break
      case 'content':
        buildContentSlide(pptx, slide, data.subject, data.grade, contentSlideIndex++)
        break
      case 'activity':
        buildActivitySlide(pptx, slide, data.subject, data.grade)
        break
      case 'key_concepts':
        buildKeyConceptsSlide(pptx, slide, data.subject, data.grade)
        break
      case 'discussion':
        buildDiscussionSlide(pptx, slide, data.subject, data.grade)
        break
      case 'summary':
        buildSummarySlide(pptx, slide, data.subject, data.grade)
        break
    }
  }

  return await pptx.write({ outputType: 'nodebuffer' }) as Buffer
}
